name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11 fox x64
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and Test with Gradle
        run: ./gradlew clean test jacocoTestReport sonarqube
      - name: Assemble Artifact
          run: ./gradlew assemble