version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run: gradle clean test
      - run: gradle assemble
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/libs
          destination: libs